### PR TITLE
Add support and handling for all irregular whitespaces listed in Eslint no-irregulare-whitespace rule + tests

### PR DESCRIPTION
**Pull request by MohamedLamineAllal**
Here as i said i made the changes!

List of irregulars whitespaces!

https://eslint.org/docs/rules/no-irregular-whitespace

This PR implement the handling! And tests!

To note: The tests pass! And with that too, i tested manually against ALT + SPACE and using the debugger! It's working 100%!

For npm package.json! using npx allow to run the local version of typescript!

For readme: I added a section for release note!  Didn't put the version number (left it with 0.0.x) I let it for you to handle it!
Same for the publishing version!

I added too the irregular whitespaces list (with eslint link).

Lastely, a suggestion: You may like to add my article about irregular spaces to the readme, which talk well about the irregular whitespaces! (if you see it valuable)!

### CODE REVIEW

**Comment by karlito40** [comment]
Nice it looks good for me.

I will test it tomorrow and push a new version in the same time if it works. I'm still at work right now :blush:  

> You may like to add my article about irregular spaces to the readme, which talk well about the irregular whitespaces! 

Yea sure. You deserve it. Don't hesitate to add it directly in this MR - or i will do it tomorrow if you don't have the time.  

And thanks for the grammar. I'm not that good in english as you may notice :eyes:

**Comment by MohamedLamineAllal** [comment]
Cool bro!
God bless you! For English i'm not a language Nazi lol! And i wonder how we do compare. 

For adding my article it's more about how you see it yourself. I see value. I can add it. But may be u like to choose where to put it. Well i'm adding a section. Check and decide.

**Comment by karlito40** [comment]
That's fine for me 👍

**Comment by karlito40** [comment]
The new version is live. 

 It has been release with a new icon and a fresh contributors section 👍

**Comment by MohamedLamineAllal** [comment]
Pretty awesome! Thank you again for the package!

**Pull request merged**
